version: '3.8'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: franquias
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/mysql:/docker-entrypoint-initdb.d